### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by samdoidge** [nquinlan/jekyll-pageless-redirects#6]
Edit: I get the following error when serving locally: `/Library/Ruby/Gems/2.0.0/gems/jekyll-2.1.1/lib/jekyll/cleaner.rb:59: stack level too deep (SystemStackError)`
Removing the plugin from _plugins fixes this.

So I have added the plugin and redirect into my Jeykll [repo](https://github.com/samdoidge/samdoidge.github.io)

Custom domain: [http://samdoidge.com](http://samdoidge.com/)

I use the master branch as from the [github article](https://help.github.com/articles/using-jekyll-with-pages):
For User Pages, use the master branch in your username.github.io repository. For Project Pages, use the gh-pages branch in your project's repository.

Outcome: 404 Error

**Comment by mhluska** [comment]
I fixed it by changing the relevant portion in `def generate_aliases` to this:

```
index_path = alias_index_path.split('/')[0, sections + 1].join('/')
next if index_path.empty?

@site.static_files << Jekyll::PagelessRedirectFile.new(@site, @site.dest, index_path, '')
```
