### ISSUE TITLE
works on localhost but not live

### ISSUE THREAD

**Issue by taigeair** [nquinlan/jekyll-pageless-redirects#9]
I added the plugin to the _plugins directory and created a _redirects.htaccess file in root. It works on localhost, so I committed it and push to github master, but when I test it on live it doesn't redirect. Do you know what the issue could be?

**Comment by taigeair** [comment]
Is this why? http://stackoverflow.com/questions/20369397/jekyll-plugin-not-work-on-github

**Comment by yeah568** [comment]
Yep, Github doesn't run any plugins except for a select few. You'll have to either not use any, or run Jekyll locally and only push up the _site folder (the already rendered output).
[Github documentation](https://help.github.com/articles/using-jekyll-plugins-with-github-pages/)
[Jekyll documentation](http://jekyllrb.com/docs/plugins/)
